algorithm: fixmatch
save_dir: ./saved_models/usb_cv/
save_name: fixmatch_imagenet_100000_0
resume: True
load_path: ./saved_models/usb_cv//fixmatch_imagenet_100000_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 500
num_train_iter: 512000
num_log_iter: 256
num_eval_iter: 5120
batch_size: 256
eval_batch_size: 512
num_warmup_iter: 5120
num_labels: 100000
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.7
ulb_loss_ratio: 10.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.001
layer_decay: 0.75
momentum: 0.9
weight_decay: 0.01
amp: True
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir: ./data
dataset: imagenet
train_sampler: RandomSampler
num_classes: 1000
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10002
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/mae_pretrain_vit_base.pth
