algorithm: mixmatch
resume: True
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 25600
num_warmup_iter: 1280
num_log_iter: 64
num_eval_iter: 512
num_labels: 250
batch_size: 32
eval_batch_size: 32
ema_m: 0.0
mixup_alpha: 0.5
T: 0.5
ulb_loss_ratio: 100
unsup_warm_up: 0.4
mixup_manifold: True
uratio: 1
use_cat: False
optim: AdamW
lr: 5e-07
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: bert_base_uncased
net_from_name: False
data_dir: ./data
dataset: yelp_review
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
max_length: 512
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10048
dist_backend: nccl
gpu: None
