algorithm: supervised
save_dir: ./saved_models/usb_cv/
save_name: supervised_imagenet200_4000_v1
resume: True
load_path: ./saved_models/usb_cv//supervised_imagenet200_4000_v1/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 250
num_train_iter: 20000
num_log_iter: 5
num_eval_iter: 20
batch_size: 32
eval_batch_size: 256
num_warmup_iter: 0
num_labels: 4000
uratio: 1
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 3e-4
layer_decay: 0.75
momentum: 0.9
weight_decay: 0.05
amp: True
clip: 0.0
use_cat: True
net: vit_base_patch16_224
net_from_name: False
data_dir: ./data
dataset: imagenet
train_sampler: RandomSampler
num_classes: 200
num_workers: 16
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10006
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/mae_pretrain_vit_base.pth
